from pathlib import Path

CONFIG_FILE_PATH = Path("config/config.yaml")
PARAMS_FILE_PATH = Path("params.yaml")

MLFLOW_URI = "MLFLOW_TRACKING_URI"
MLFLOW_PASS = "MLFLOW_TRACKING_PASSWORD"
MLFLOW_USERNAME = "MLFLOW_TRACKING_USERNAME"